import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "@/components/Navbar";
import ReduxProvider from "@/redux/ReduxProvider";

const KumbhSans = localFont({
  src: [
    { path: "./fonts/KumbhSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/KumbhSans-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-kumbh-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` flex flex-col mx-auto lg:w-[85%] ${KumbhSans.className}`}>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
