import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const KumbhSans = localFont({
  src: [
    { path: "./fonts/KumbhSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/KumbhSans-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-kumbh-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${KumbhSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
